version: "3"

services:
  retrival-system:
    build:
      context: .
      dockerfile: ./docker_build/Dockerfile
    volumes: 
      - ./retrieval_system:/retrieval_system   
    ports:
      - "8080:5000"
    environment:
      FLASK_DEBUG: 1