version: "3"

services:
  retrival-system:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: [./retrival_system/data:/data]
    ports:
      - "8080:5000"
    environment:
      FLASK_DEBUG: 1