version: "3"

services:
  retrival-system:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./retrival_system:/retrival_system
      # - ./retrival_system/data:/data
      # - ./retrival_system/web_app:/web_app      
    ports:
      - "8080:5000"
    environment:
      FLASK_DEBUG: 1